# cargo-features = ["edition2024"] # DOCS: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2024

[package]
name = "thirdeye"
version = "0.1.0"
edition = "2021"
description = "An under development search engine written in rust."

[dependencies]
